source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'activerecord'
gem 'rake'
gem 'pg'
gem 'pry'
gem 'rack-test', '0.6.3'
gem 'rack'
gem 'minitest', '~> 5.1'
gem 'factory_bot', '~> 4.0'
gem 'faker'